# Generated by Django 3.0.7 on 2020-07-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20200704_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.TextField(blank=True, verbose_name='source'),
        ),
    ]
