# Generated by Django 3.0.7 on 2020-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0013_photo_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='title'),
        ),
    ]
